judge-host-exceptions:
  codes:
    00000: 一切正常
    A0001: 用户错误
    A0002: 用户表单错误
    A0003: 用户名或密码错误
    A0004: 权限错误
    A0005: 不支持的判题偏好
    A0006: 请求内容为空
    B0001: 服务器错误
    B1002: 找不到文件依赖
    B1003: 找不到文件
    B1004: 判题需求文件下载失败
    B1005: 判题服务器负载已满
    B1006: 当前有任务正在进行中, 无法修改
    B1007: 文件不存在